version: '3.1'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: R00tr00t
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 4080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: R00tr00t

